### PR TITLE
BBFS implementation

### PR DESCRIPTION
**Pull request by StjepanBM1**
Just an basic implementation. Do **NOT** merge.

Prints out data on the first sector starting from the 3rd byte.

### CODE REVIEW

**Comment by StjepanBM1** [comment]
I was supposed to make a commit, but I forgot. Lmao

**Comment by Andrej123456789** [comment]
Seems ok for now

**Comment by StjepanBM1** [comment]
Read block support coming by 22:00 today, expect it sooner

**Comment by Andrej123456789** [comment]
Cool. New Termi release coming for few minutes

**Comment by StjepanBM1** [comment]
Ok, now you can merge

**Review by Andrej123456789 — APPROVED** [review]
Great job!

**Pull request merged**
